openapi.yaml

fix enum value for statusChangeReason

---

openapi.yaml

consistancy with AnomalieAdresse

---

openapi.yaml

Specify the unit to use for durations

---

ipe.drawio.svg
openapi.yaml

fix oneOf/anyOf

---

ipe.drawio.svg
openapi.yaml

31 post oc

---

openapi.yaml

doc: no ref to the proxified architecture

---

README.md

changer readme rejet oc pour ticket existant

---

README.md
openapi.yaml

remplacer CANCELLED par CANCELED

---

README.md

modifier le readme : "JPEG" remplacer par "JPEG ou PNG".

---

README.md
openapi.yaml

fixer le délai max de reprise par l'OI

---

openapi.yaml

Ajouter le champs activationRate

---

openapi.yaml

add  recoveryQuantity in malfacon

---

README.md

Restreindre les champs modifiables

---

README.md

delete facturation in readme

---

README.md

replace crise ->  situations exceptionnelles

---

README.md

update delai max description

---

README.md

add RG status creating

---

openapi.yaml

mise à jour code fault and localisation

---

openapi.yaml

suppression code insee de la malfacon present sur les equipements

---

openapi.yaml

Ajout de l'entité manipulée dans les URI

---

openapi.yaml

used V1 common interop

---

openapi.yaml

Passage de Malfacon en OAS 3.0.3.
Nécessite que common/v1 soit également en OAS 3.0.3 via la PR https://github.com/before-interop/common/pull/40

Passage en Open API 3.0.3

---

openapi.yaml

Ajout de champs sur certains schémas

---

openapi.yaml

add description codefault and localizationDetails

---

openapi.yaml

add discripminator for opticalRoute

---

openapi.yaml

Fix wrong ref url

---

openapi.yaml

change RG optical route

---

openapi.yaml

change type  malfacon.amontpm.oi

---

openapi.yaml

fix faultDetailsCode

---

openapi.yaml

Closes #127 and #129 
Has to be validated together with [https://github.com/before-interop/common/pull/64](https://github.com/before-interop/common/pull/64)

Refonte attachment

---

openapi.yaml

Ajout referencePBO et referencePTO dans la route optique finale

---

openapi.yaml

pbo et pto facultatif sur mafacon ccf
